version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: crypto_postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=db
    volumes:
      - crypto_postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - crypto-network
volumes:
  crypto_postgres_data:

networks:
  crypto-network:
    driver: bridge